import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedCompanyProfiles1000000000006 implements MigrationInterface {
  name = 'SeedCompanyProfiles1000000000006';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO "company_profiles" (category, company_name, owner_name, company_active_accounts, personal_active_accounts) VALUES
      ('C', 'PREMIUM EXIM TRADING LLC', 'MUJAHID KHAN', '', 'WIO, MASHREQ NEO, EIB'),
      ('C', 'CARGOLIC SHIPPING & LOGISTICS LLC', '', '', ''),
      ('C', 'AMINEX GENERAL TRADING LLC', 'HAFIZ ATTIQ AHMAD KHAN', 'ADIB, SIB, UBL, NBF, FAB', 'WIO, MASHREQ NEO, EIB'),
      ('C', 'MAPLESKY EVENTS MANAGEMENT LLC', '', 'ADIB, MASHREQ, SIB, NBF', ''),
      ('C', 'NETFLOW TECHNOLOGIES LLC', '', 'EIB, SIB, NBF', ''),
      ('C', 'BLACK PEPPER REAL ESTATE', 'IBTASAM SHAHZAD MALIK', '', 'EIB'),
      ('B', 'BLACK PEPPER GENERAL TRADING LLC', '', 'ADIB, NBF, SIB', ''),
      ('B', 'GRENEW TECHNOLOGY', '', '', ''),
      ('A', 'GRENEW FZE - (HFZA)', 'SANDEEP KEDIA', 'NBF, SIB', ''),
      ('B', 'GRENEW - PINNACLE (JAFZA)', '', 'NBF', ''),
      ('A', 'PINNACLE GROUPS FZE', '', 'NBF, SIB, UBL', 'SCB, MASHREQ'),
      (NULL, 'PINNACLE INT.', '', 'ADIB, FAB, SIB', ''),
      (NULL, 'PINNACLE EXIM IT SOLUTION LLC', 'PINNACLE GROUPS / QUICKTOUCH TECHNOLOGIES (MOHIT MANAGER)', 'WIO', ''),
      ('C', 'RHINE MULTY TRADING LLC', 'SURESH RAW APPALASAMY', 'NBF', ''),
      ('C', 'RHINE BULLIONS', '', '', ''),
      ('C', 'HEDGES GOODS WHOLESALERS LLC', 'MOHD SHOEB IQBAL', 'FAB', ''),
      ('C', 'BLACK PEPPER TOURISM LLC', 'ROSHAN ZAMEER', 'MASHREQ', 'MASHREQ, FAB'),
      ('C', 'RED FIRE SHIPPING & LOGISTICS', 'RAJESH MONGA', '', 'MASHREQ NEO, LIV'),
      ('C', 'BLUE FIRE', 'ASHISH DILIP KUMAR', '', ''),
      ('C', 'STRATOSPHERE EVENTS MANAGEMENT LLC', 'KHUSHNOOD', 'SIB, NBF', 'MASHREQ NEO, EIB, FAB'),
      ('B', 'ROYAL EN EM GENERAL TRADING LLC', '', 'ENBD, FAB, NBF, SIB', ''),
      ('C', 'UNNATI GENERAL TRADING LLC FZ', '', 'ADIB, SIB, WIO', ''),
      ('C', 'STRATOSPHERE INFORMATION TECHNOLOGY LLC', '', 'ADIB, SIB, WIO, NBF', ''),
      ('C', 'ZENTIWA COMMERCIAL BROKERS LLC', 'SARBA BAHADUR PUN', 'SIB, ADIB', 'WIO'),
      ('C', 'BOLD GROWTH GENERAL TRADING LLC', '', '', ''),
      ('C', 'RHYTHM LOGISTICS', '', '', ''),
      ('C', 'SPINFLUENCE IT SOLUTIONS LLC', 'JOSEPH JOHNSON DSILVA', 'EIB, SIB, ADIB', 'WIO'),
      ('C', 'IDEA GROVE GENERAL TRADING LLC', '', 'ADIB, EIB, RAK, SIB', ''),
      ('C', 'OPTICORE INFORMATION TECHNOLOGY', 'MADAN BHANDARI', 'ADIB, SIB', 'WIO, EIB'),
      ('C', 'VELOCITY STAR LOGISTICS', '', '', ''),
      ('C', 'CROSSFIT GENERAL TRADING LLC', '', 'MASHREQ, SIB, ADIB', ''),
      ('B', 'QUANTEM QUEST GENERAL TRADING LLC', 'ROHIT BHARADWAJ', 'WIO', 'EIB, WIO'),
      ('B', 'PARADE WAVE TECHNOLOGIES LLC', '', '', ''),
      ('C', 'ALPHA SANTRY INFORMATION TECHNOLOGY', 'TANVEER HUSAIN BUKHARI', '', 'MASHREQ, FAB'),
      ('C', 'M J S STAR GENERAL TRADING LLC', '', 'NBF, EIB, SIB, UBL', ''),
      ('C', 'TRADERS VENTURES FORFAITING LLC', 'RAYMOND DOMINIC', 'EIB, ADIB', 'WIO'),
      ('A', 'COMIDA GOODS WHOLESALERS LLC', 'INAYATULLAH SHARAFATULLAH', 'NBF, ADIB, UBL, SIB, FAB', 'MASHREQ NEO'),
      ('B', 'CAPS LOCK GENERAL TRADING LLC', 'DILIP KUMAR CHATURVEDI', 'FAB, SIB, WIO', 'WIO'),
      ('B', 'GLUCKRICH HOLDING LLC-FZ', 'SANDEEP KUMAR DHANUKA', 'INDUS IND, BANQUE MISR, NBF, UBL', ''),
      ('B', 'ENFLOW GENERAL TRADING LLC', 'VISHAL BAKLE', 'SIB, UBL, ADIB', 'WIO, ENBD'),
      ('A', 'INFINITY FORTUNE TRADING LLC', 'GURDEV SINGH', 'MASHREQ, WIO, ADIB, SIB, NBF, HBZ', 'ENBD'),
      ('B', 'SHRIJI INTERNATIONAL LLC-FZ', 'ANAND (MANAGER)', 'EIB', ''),
      ('B', 'AGNIRA INTERNATIONAL LLC-FZ', 'ASHISH DHANUKA (MANAGER)', 'WIO, EIB', ''),
      ('C', 'CARNIFY INTERNATIONAL LLC', 'HARWINDER SINGH / ADITYA TRIVEDI', 'ENBD, EIB', 'MASHREQ NEO'),
      ('A', 'BULLFROG TRADING LLC', 'BARRY HENRY ROSHIER', 'ADIB, NBF, FAB, SIB', 'MASHREQ NEO'),
      ('C', 'SWIFT BRIDGE GENERAL TRADING LLC', 'LOVEDEEP SINGH', 'SIB, MASHREQ, ENBD, ADIB, WIO', 'MASHREQ NEO'),
      ('B', 'SILVERSTONE INTERNATIONAL TRADING LLC-FZ', 'PANKAJ CHADHA', 'ADIB, ENBD', 'EIB, MASHREQ'),
      ('A', 'GUJRAT PAPER & PLASTIC MANUFACTURING', 'INFINITY / GURDEV (MANAGER)', 'RAK, ADCB, ADIB, SIB, NBF', 'ADIB'),
      ('C', 'ORBIT PLUS GENERAL TRADING LLC', 'ROSHAN ZAMEER', 'SIB, MASHREQ, ADIB, UBL, WIO', ''),
      ('B', 'GOLDENOVA GENERAL TRADING LLC', 'RAYMOND DOMINIC', 'MASHREQ, RAK, UBL', 'WIO, ENBD'),
      ('C', 'PANTRADE RWA INFORMATION TECHNOLOGIES LLC', 'AYAZ MUSTAJAB ALI', '', ''),
      ('A', 'ADVANCE RECYCLING TECHNOLOGY (ART)', 'INAYATULLAH SHARAFATULLAH', 'RAK, NBF, ADCB', '')
      ON CONFLICT (company_name) DO NOTHING
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM "company_profiles"`);
  }
}
